-- ============================================
-- MIGRATION: Add 'accepted' status + applicant_score column
-- ============================================
-- This migration:
--   1. Updates the CHECK constraint on applications.status to allow
--      the new admin-assignable 'accepted' status.
--   2. Adds the applicant_score column used when an admin accepts
--      an applicant (score is required before status can be set).
--
-- Safe to run multiple times.
-- ============================================

-- 1. Add applicant_score column (if not exists)
ALTER TABLE applications
  ADD COLUMN IF NOT EXISTS applicant_score VARCHAR(50);

-- 2. Drop the existing CHECK constraint (name is auto-generated by Postgres
-- when the column was created inline, typically "applications_status_check").
DO $$
DECLARE
  constraint_name text;
BEGIN
  SELECT con.conname INTO constraint_name
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  WHERE rel.relname = 'applications'
    AND con.contype = 'c'
    AND pg_get_constraintdef(con.oid) ILIKE '%status%';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE applications DROP CONSTRAINT %I', constraint_name);
  END IF;
END $$;

-- 3. Re-add the CHECK constraint with 'accepted' included.
ALTER TABLE applications
  ADD CONSTRAINT applications_status_check CHECK (status IN (
    'submitted', 'pending_review', 'incomplete_document', 'approved_to_attend_exam',
    'passed_with_exemption', 'application_approved', 'accepted', 'reserved', 'rejected'
  ));
